# The name of your site
name: UConn Banner

# The secondary title for your site. Typically your department, school or college.
department: University Communications

# The URL for your department
department_url: http://communications.uconn.edu/

# Show the site header below the blue banner?
# This should almost always be set to true.
show_header: true

# Edit <form> markup to match your site search code.
# Or, set to 'search: false' to disable the search form altogether.
search: |
        <form class="form-search">
            <input type="text" class="input-medium" placeholder="Search this site...">
            <button type="submit" class="btn">Search</button>
        </form>


# Server settings for `jekyll serve`
port:        4000
baseurl:     /
